### PR TITLE
Migrate to grpc-js

### LINKED ISSUE #113: Investigate node function on PKS crash loop
The node function is consistently entering a crash loop when running on PKS. It works on every other k8s runtime that we test.

See https://dev.azure.com/projectriff/projectriff/_build/results?buildId=2750&view=logs&jobId=88362a0d-4bdb-5566-6120-ca9d0da39f74&taskId=99c6fbac-d6aa-5ac3-890e-a553abc603e4&lineStart=61&lineEnd=62&colStart=1&colEnd=1

### PR DESCRIPTION
**Pull request by fbiville**
Fixes #113

### CODE REVIEW

**Comment by fbiville** [comment]
Biggest changes:

- proto has to be loaded at runtime
- plain old Javascript objects are generated for the gRPC data types (no accessor methods generated)
- gRPC map is generated as an object
- server.bind -> server.bindAsync
- cancelWithStatus -> sendError


Possible source of worry (i.e. investigation needed):
 - output frames payloads are always wrapped in Buffer (see https://github.com/projectriff/node-function-invoker/pull/181/files#diff-9d5cdba041794f2e2a88cab243212e23)

**Comment by fbiville** [comment]
I managed to successfully deploy and run the function on the core runtime (I have a strange issue with Knative).

**Comment by fbiville** [comment]
> Do you have a sense of the performance impact? if any

I have spent a significant time getting a proper riff install on a PKS cluster, so I have not started looking at this particular aspect yet.

**Comment by murgatroid99** [comment]
Hi,
I'm the grpc maintainer; I got here following the link from that issue about `server.bind` and I realized that I could help you simplify this migration. First, you can actually continue using the same proto Message classes you are currently using. The most recent version of `grpc-tools` has an option "generate_package_definition" that makes it generate a file that outputs the same kind of object that `protoLoader.load` outputs, so you can pass that into `grpc.loadPackageDefinition`. Using that option just requires changing part of your `grpc-tools` invocation like this: `--grpc_out=generate_package_definition:./codegen`.

Second, this doesn't necessarily help with this migration exactly but it explains why this part changed: the intended way of having a server end a call with a non-OK status is to call `stream.emit('error', status)`. Seeing your code I realize that that's not obvious and it would be better to have something like `stream.endWithStatus(statusObject)`.

**Comment by fbiville** [comment]
@murgatroid99 thanks for the feedback (apologies for the delay, I was in "staycation" until today).
I'll try your suggestion to reduce the PR size, many thanks!

Regarding the emission of errors, does this mean that:
```javascript
                grpcStream.call.sendError({
                    code: grpc.status.INVALID_ARGUMENT,
                    details: `${errors.reserved_prefixes.NOT_ACCEPTABLE}: ${err.cause}`,
                });
```
can be replaced with:
```javascript
                grpcStream.emit('error', {
                    code: grpc.status.INVALID_ARGUMENT,
                    details: `${errors.reserved_prefixes.NOT_ACCEPTABLE}: ${err.cause}`,
                });
```
?

**Comment by fbiville** [comment]
Converting this PR to draft. I'll try to open another one with aforementioned suggestions.

**Comment by murgatroid99** [comment]
@fbiville That is what I meant about emitting errors.

I don't see anything wrong with how you're importing the package definition and I don't know why it would be returning UNIMPLEMENTED errors.

**Pull request merged**
