### PR TITLE
Add support for gRPC

### PR DESCRIPTION
**Pull request by scothis**
Implements a gRPC server for the riff MessageFunction service.

- Dynamically loads function.proto to create the service rather than
  using statically generated code. In tests, load time is twice as fast
  using dynamic loading and offers plain JS type support.
- Looks for `Content-Type` and `Accept` headers (case sensitive) to
  support content negotiation supporting:
  - `text/plain`
  - `application/octet-stream`
  - `application/json`
- Maintains compatibility with functions invocable via HTTP

The `error` message header indicates when an invocation failed.
Errors are either client or server errors. Client errors can often
be resovled by using a different Content-Type or Accept header value.

The following error codes are used:
- `error-server-function-invocation`:
  The function being invoked threw an error
- `error-client-content-type-unsupported`:
  The message's Content-Type is not supported
- `error-client-accept-type-unsupported`:
  The server is unable to satisfy the client's acceptable types
- `error-client-unmarshall`:
  An error occured while unmarshall the input message's payload. For
  example, invalid JSON.
- `error-client-marshall`:
  An error occured while marshalling the output message's payload. For
  example, JSON stringifying object cycles.

While streaming can be added in the future, all invocations are assumed
to be request-reply for now.

Issue: #12

### CODE REVIEW

**Comment by jldec** [comment]
looks good @scothis 

Could we add a note in the function-proto [readme](https://github.com/projectriff/function-proto/tree/master/node) explaining how we publish the function.proto to [@projectriff/function-proto](https://www.npmjs.com/package/@projectriff/function-proto) on npm, and consume it dynamically from the sidecar. 

I would also suggest adding a short note to the main readme here documenting the 2 protocols and how they work (sync, async, streams, lifecycle hooks) with a few examples.

**Comment by ericbottard** [comment]
> the 2 protocols

Does that refer to `http` and `gRPC`? I thought we were keeping only gRPC for now, so why bother document http?

**Comment by jldec** [comment]
@ericbottard, even if we think the 2 protocols are functionally equivalent, it would be better to deprecate the http protocol over one or two release cycles (or at least spread over a couple of PRs) giving others a chance to test their functions first.

**Comment by jldec** [comment]
Let's try to keep the readme in-sync with what's in the codebase (even if we just copy the examples out of the PR comments) and help developers who want to understand what we're doing.

**Comment by scothis** [comment]
It's worth deprecating HTTP support now and removing it after 0.0.4. 

The riff cli will need to be update the generated yaml to set `protocol: grpc` and for the generated Dockerfile to extend from the 0.0.4-snapshot invoker. Since our practice is to have the CLI point to the last invoker release, we'll want 0.0.4 to support both grpc and http, then remove http in 0.0.5.

**Pull request merged**
