### PR TITLE
set invalid_input error to grpc status code invalid_arg

### PR DESCRIPTION
**Pull request by cz9779**
grpc returns invalid arg code with error type INVALID_INPUT when encounter unmarshall errors, so that streaming-http-adapter can handle invalid json input as http 400 bad request

### CODE REVIEW

**Comment by fbiville** [comment]
Related adapter PR is: https://github.com/projectriff/streaming-http-adapter/pull/64/

**Comment by elbandito** [comment]
> Bad request is an HTTP concept that isn't appropriate for a streaming protocol.
> 
> I do think it's worth being able to distinguish input related errors form function related errors (in HTTP speak 4xx errors from 5xx errors)

Hi @scothis As the PR implies, we'd like to communicate via HTTP error to the consumer of the function if the `json` payload they pass is malformed.  Do you have any guidance around how we could/should approach this?

**Comment by scothis** [comment]
> Hi @scothis As the PR implies, we'd like to communicate via HTTP error to the consumer of the function if the json payload they pass is malformed. Do you have any guidance around how we could/should approach this?

I'm in favor of being able to respond to the HTTP request with an appropriate error code.  However, because HTTP is terminated in the streaming-http-adapter, HTTP semantics shouldn't surface within the invoker. Instead, we need to return an appropriate error code for a stream with an invalid message. Then in the streaming-http-adapter covert that streaming error into an HTTP 400 response.

The simplest possible way to enhance this PR to something that aligns is to rename `BAD_REQUEST` to `BAD_INPUT` (still not crazy about that name), but I'll defer to @fbiville for other name suggestions that are appropriate for a stream.

**Comment by cz9779** [comment]
> fbiville

**Comment by fbiville** [comment]
@cz9779 BAD_INPUT or BAD_INPUT_SIGNAL sound like good options to me

**Pull request merged**
